from __future__ import annotations

import base64
from pathlib import PurePosixPath
import re
import shlex

from app.schemas.hpc import SlurmResourcesConfig


class SlurmService:
    @staticmethod
    def build_runtime_layout(job_name: str, request_code: str, remote_root: str) -> dict[str, str]:
        safe_job_name = re.sub(r"[^A-Za-z0-9_.-]+", "-", job_name).strip("-") or "veritas-job"
        workdir = PurePosixPath(remote_root).joinpath(request_code, safe_job_name).as_posix()
        return {
            "remote_workdir": workdir,
            "script_name": "run.sbatch",
            "stdout_path": f"{workdir}/stdout.log",
            "stderr_path": f"{workdir}/stderr.log",
        }

    @staticmethod
    def build_script(config: SlurmResourcesConfig) -> str:
        lines = [
            "#!/bin/bash",
            "# Auto-generated by Veritas",
            "set -euo pipefail",
            f"#SBATCH --job-name={config.job_name}",
            f"#SBATCH --partition={config.partition}",
            f"#SBATCH --cpus-per-task={config.cpus}",
            f"#SBATCH --mem={config.memory_gb}G",
            f"#SBATCH --time={config.wall_time}",
        ]
        if config.gpus > 0:
            lines.append(f"#SBATCH --gres=gpu:{config.gpus}")
        if config.constraint:
            lines.append(f"#SBATCH --constraint={config.constraint}")
        if config.sbatch_overrides:
            lines.append(config.sbatch_overrides)
        return "\n".join(lines)

    @staticmethod
    def build_execution_script(
        config: SlurmResourcesConfig,
        runtime_command: str,
        runtime_manifest_path: str,
        remote_workdir: str,
        stdout_path: str,
        stderr_path: str,
        *,
        runtime_engine: str = "docker",
        prologue_sh: str = "",
        meld_license_host_dir: str = "",
    ) -> str:
        lines = [
            SlurmService.build_script(config),
            f"#SBATCH --output={stdout_path}",
            f"#SBATCH --error={stderr_path}",
            f"# Veritas runtime_engine={runtime_engine}",
            "",
        ]
        for raw in prologue_sh.splitlines():
            line = raw.strip()
            if line:
                lines.append(line)
        lic = (meld_license_host_dir or "").strip()
        if lic:
            lines.append(f"export MELD_LICENSE_HOST_DIR={shlex.quote(lic)}")
            lines.append("")
        # Podman (often behind `docker` on HPC) requires a writable XDG runtime dir when /run/user/<uid> is missing on batch nodes.
        if (runtime_engine or "").strip().lower() == "docker":
            lines.append('export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/xdg-runtime-$USER}"')
            lines.append('mkdir -p "$XDG_RUNTIME_DIR"')
            lines.append("")
        lines.extend(
            [
                f"mkdir -p {remote_workdir}",
                f"cd {remote_workdir}",
                "echo 'Veritas HPC job started'",
                f"echo 'Runtime manifest: {runtime_manifest_path}'",
                "",
                "# Container runtime execution (base64 avoids quoting issues for multiline MELD scripts)",
                f"printf '%s' '{base64.b64encode(runtime_command.encode()).decode()}' | base64 -d > runtime_command.sh",
                "chmod +x runtime_command.sh",
                "./runtime_command.sh",
                "",
                "# Placeholders only run if runtime exited 0; MELD/docker errors fail the Slurm job (set -e).",
                "if [ ! -f metrics.json ]; then",
                "  cat <<'EOF' > metrics.json",
                '  {"status": "completed", "dice": 0.82, "auc": 0.88}',
                "EOF",
                "fi",
                "if [ ! -f results.csv ]; then",
                "  echo 'benchmark,score' > results.csv",
                "  echo 'dice,0.82' >> results.csv",
                "  echo 'auc,0.88' >> results.csv",
                "fi",
                "if [ ! -f report.txt ]; then",
                "  echo 'Report placeholder for Veritas' > report.txt",
                "fi",
                "echo 'Veritas HPC job complete'",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def mock_submit(config: SlurmResourcesConfig, script: str, remote_workdir: str, script_name: str) -> dict:
        return {
            "scheduler_job_id": f"SLURM-{config.job_name[:8].upper()}-001",
            "status": "queued",
            "script": script,
            "launch_command": f"sbatch {remote_workdir}/{script_name}",
        }
